# Generated by Django 3.2.16 on 2022-12-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('catagory', models.CharField(choices=[('BAS', 'BASIC'), ('STN', 'STANDARD'), ('LUX', 'LUXURIUS'), ('ROY', 'ROYAL')], max_length=3)),
                ('beds', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
