# Generated by Django 3.2.16 on 2022-12-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnbhouse', '0002_bookings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='catagory',
            new_name='category',
        ),
    ]
