# Generated by Django 3.2.16 on 2022-12-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbhouse', '0003_rename_catagory_house_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='check_out',
            field=models.DateTimeField(),
        ),
    ]
