# Generated by Django 3.2.16 on 2022-12-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbhouse', '0005_rename_guest_bookings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='slug',
            field=models.SlugField(default='test-description'),
            preserve_default=False,
        ),
    ]
