# Generated by Django 3.2.16 on 2022-12-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbhouse', '0006_house_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(),
        ),
    ]
