# Generated by Django 3.2.16 on 2022-12-16 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bnbhouse', '0007_alter_house_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
