# Generated by Django 3.2.16 on 2022-12-19 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bnbhouse', '0009_auto_20221219_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='check_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='check_out',
            field=models.DateTimeField(),
        ),
    ]
