# Generated by Django 3.2.16 on 2022-12-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbhouse', '0012_auto_20221220_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='check_in',
            field=models.DateTimeField(),
        ),
    ]
