# Generated by Django 3.2.16 on 2022-12-29 14:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnbhouse', '0013_alter_bookings_check_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='slug',
        ),
        migrations.AddField(
            model_name='house',
            name='house_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
